### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by Quenty31**

### CODE REVIEW

**Comment by Michal-Szczepaniak** [comment]
Thank you!

**Comment by Quenty31** [comment]
Some strings seem to be missing such as «Open file...» (would be "Ouvrir un fichier...") and «Open URL stream...» (would be "Ouvri flux réseau...") and «Select localation» (would be "Sélectionnez répertoire")

**Comment by Michal-Szczepaniak** [comment]
Ah give me second

**Comment by Michal-Szczepaniak** [comment]
Langs updated!

**Pull request merged**
